spring:
  datasource:
    url: jdbc:mysql://localhost:3306/routy
    username: your-username
    password: your-password
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: your-jwt-secret

server:
  port: 8011